[versions]
ktor = "3.3.3"
komponenter = "1.0.461"
tilgang = "1.0.170"
utbetaling = "0.0.68"
brev = "0.0.202"
meldekort = "0.0.161"
apiIntern = "0.0.21"
junit = "6.0.1"
testcontainers = "2.0.2"

[libraries]
ktorClientContentNegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktorServerContentNegotation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
ktorHttpJvm = { module = "io.ktor:ktor-http-jvm", version.ref = "ktor" }
ktorServerNetty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }
ktorServerTestHost = { module = "io.ktor:ktor-server-test-host", version.ref = "ktor" }
ktorServerStatusPages = { module = "io.ktor:ktor-server-status-pages", version.ref = "ktor" }
ktorSerializationJackson = { module = "io.ktor:ktor-serialization-jackson", version.ref = "ktor" }

# Komponenter
json = { module = "no.nav.aap.kelvin:json", version.ref = "komponenter" }
dbconnect = { module = "no.nav.aap.kelvin:dbconnect", version.ref = "komponenter" }
verdityper = { module = "no.nav.aap.kelvin:verdityper", version.ref = "komponenter" }
dbmigrering = { module = "no.nav.aap.kelvin:dbmigrering", version.ref = "komponenter" }
httpklient = { module = "no.nav.aap.kelvin:httpklient", version.ref = "komponenter" }
infrastructure = { module = "no.nav.aap.kelvin:infrastructure", version.ref = "komponenter" }
server = { module = "no.nav.aap.kelvin:server", version.ref = "komponenter" }
tidslinje = { module = "no.nav.aap.kelvin:tidslinje", version.ref = "komponenter" }
motor = { module = "no.nav.aap.kelvin:motor", version.ref = "komponenter" }
motorApi = { module = "no.nav.aap.kelvin:motor-api", version.ref = "komponenter" }
gateway = { module = "no.nav.aap.kelvin:gateway", version.ref = "komponenter" }
dbtest = { module = "no.nav.aap.kelvin:dbtest", version.ref = "komponenter" }
motorTestUtils = { module = "no.nav.aap.kelvin:motor-test-utils", version.ref = "komponenter" }
tilgangKontrakt = { module = "no.nav.aap.tilgang:api-kontrakt", version.ref = "tilgang" }
tilgangPlugin = { module = "no.nav.aap.tilgang:plugin", version.ref = "tilgang" }
utbetalKontrakt = { module = "no.nav.aap.utbetal:api-kontrakt", version.ref = "utbetaling" }
brevKontrakt = { module = "no.nav.aap.brev:kontrakt", version.ref = "brev" }
meldekortKontrakt = { module = "no.nav.aap.meldekort:kontrakt", version.ref = "meldekort" }
apiInternKontrakt = { module = "no.nav.aap.api.intern:kontrakt", version.ref = "apiIntern"}

caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version = "3.2.3" }
jacksonAnnotations = { module = "com.fasterxml.jackson.core:jackson-annotations", version = "2.20" }
jacksonDatabind = { module = "com.fasterxml.jackson.core:jackson-databind", version = "2.20.1" }
jacksonDatatypeJsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310", version = "2.20.1" }

hikariCp = { module = "com.zaxxer:HikariCP", version = "7.0.2" }
postgresql = { module = "org.postgresql:postgresql" }
flywayDatabasePostgresql = { module = "org.flywaydb:flyway-database-postgresql", version = "11.17.2" }

opentelemetryInstrumentationAnnotations = { module = "io.opentelemetry.instrumentation:opentelemetry-instrumentation-annotations", version = "2.22.0" }
opentelemetryLogbackMdc = { module = "io.opentelemetry.instrumentation:opentelemetry-logback-mdc-1.0", version = "2.22.0-alpha" }
opentelemetryKtor = { module = "io.opentelemetry.instrumentation:opentelemetry-ktor-3.0", version = "2.22.0-alpha" }

joseJwt = { module = "com.nimbusds:nimbus-jose-jwt", version = "10.6" }

logbackClassic = { module = "ch.qos.logback:logback-classic", version = "1.5.21" }
logstashLogbackEncoder = { module = "net.logstash.logback:logstash-logback-encoder", version = "9.0" }
micrometerRegistryPrometheus = { module = "io.micrometer:micrometer-registry-prometheus", version = "1.16.0" }
julToSlf4J = { module = "org.slf4j:jul-to-slf4j", version = "2.0.17" }
logbackSyslog = { module = "com.papertrailapp:logback-syslog4j", version = "1.0.0" }

avro = { module = "org.apache.avro:avro", version = "1.12.1" }
kafkaAvroSerializer = { module = "io.confluent:kafka-avro-serializer", version = "7.6.0" }
kafkaClients = { module = "org.apache.kafka:kafka-clients", version = "4.1.1" }

junitApi = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junitJupiterEngine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
junitJupiterParams = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit" }
junitPlatformLauncher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit" }

assertJ = { module = "org.assertj:assertj-core", version = "3.27.6" }
tabletest = { module = "io.github.nchaugen:tabletest-junit", version = "0.5.5" }
testcontainers = { module = "org.testcontainers:testcontainers", version.ref = "testcontainers" }
testcontainersPostgres = { module = "org.testcontainers:testcontainers-postgresql", version.ref = "testcontainers" }
testcontainersKafka = { module = "org.testcontainers:testcontainers-kafka", version.ref = "testcontainers" }
mockOauth2Server = { module = "no.nav.security:mock-oauth2-server", version = "3.0.1" }
mockk = { module = "io.mockk:mockk", version = "1.14.6" }

ktorOpenApiGenerator = { module = "no.nav:ktor-openapi-generator", version = "1.0.132" }

[bundles]
junit = ["junitApi", "junitJupiterEngine", "junitJupiterParams", "assertJ"]

[plugins]
ktor = { id = "io.ktor.plugin", version.ref = "ktor" }